name: Bralgei Shackry
favicon: null
layout_spectrum: 0.5556350210681558
typography_spectrum: 0.22367260907776654
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#4b4b4b'
    - '#8a8a8a'
    - '#d0d0d0'
    - '#ececec'
  brandStrength: 0.0625
  lightness: 0.5185942663811147
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
