name: Bralgei Shackry
favicon: null
layout_spectrum: 0.67491
typography_spectrum: 0.57725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#4b4b4b'
    - '#8a8a8a'
    - '#d0d0d0'
    - '#ececec'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
