name: Bralgei Shackry
favicon: null
layout_spectrum: 0.8212
typography_spectrum: 0.48069
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#4b4b4b'
    - '#8a8a8a'
    - '#d0d0d0'
    - '#ececec'
  brandStrength: 0.0625
  lightness: 0.3125
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
