name: Bralgei Shackry
favicon: null
layout_spectrum: 0.91534
typography_spectrum: 0.52414
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#4b4b4b'
    - '#8a8a8a'
    - '#d0d0d0'
    - '#ececec'
  brandStrength: 0.25
  lightness: 0.1875
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
