name: Bralgei Shackry
favicon: null
layout_spectrum: 0.89483
typography_spectrum: 0.48069
title: Bralgei Shackry - Shaman
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040404'
    - '#4b4b4b'
    - '#8a8a8a'
    - '#d0d0d0'
    - '#ececec'
  brandStrength: 0.1875
  lightness: 0.0625
  saturation: 0.9375
  rhythmicContrast: 0
purpose: []
